const CACHE_NAME = 'dc-dbk-v3.0';
const ASSETS = [
  "./",
  "./index.html",
  "./Thumbnails/Dryvit Lymestone - Sand 473.jpg",
  "./Thumbnails/Farmhouse Sink.jpg",
  "./Thumbnails/Hydrazo French Riveria.jpg",
  "./Thumbnails/ribbon-pattern.jpg",
  "./Thumbnails/drawings/page-01.jpg",
  "./Thumbnails/drawings/page-02.jpg",
  "./Thumbnails/drawings/page-03.jpg",
  "./Thumbnails/drawings/page-04.jpg",
  "./Thumbnails/drawings/page-05.jpg",
  "./Thumbnails/drawings/page-06.jpg",
  "./Thumbnails/drawings/page-07.jpg",
  "./Thumbnails/drawings/page-08.jpg",
  "./Thumbnails/drawings/page-09.jpg",
  "./Thumbnails/drawings/page-10.jpg",
  "./Thumbnails/drawings/page-11.jpg",
  "./Thumbnails/drawings/page-12.jpg",
  "./Thumbnails/drawings/page-13.jpg",
  "./Thumbnails/drawings/page-14.jpg",
  "./Thumbnails/drawings/page-15.jpg",
  "./Thumbnails/drawings/page-16.jpg",
  "./Thumbnails/drawings/page-17.jpg",
  "./Thumbnails/drawings/page-18.jpg",
  "./Thumbnails/drawings/page-19.jpg",
  "./Thumbnails/drawings/page-20.jpg",
  "./Thumbnails/drawings/page-21.jpg",
  "./Thumbnails/drawings/page-22.jpg",
  "./Thumbnails/drawings/page-23.jpg",
  "./Thumbnails/drawings/page-24.jpg",
  "./Thumbnails/drawings/page-25.jpg",
  "./Thumbnails/drawings/page-26.jpg",
  "./Thumbnails/drawings/page-27.jpg",
  "./Thumbnails/drawings/page-28.jpg",
  "./Thumbnails/drawings/page-29.jpg",
  "./Thumbnails/drawings/page-30.jpg",
  "./Thumbnails/drawings/page-31.jpg",
  "./Thumbnails/drawings/page-32.jpg",
  "./Thumbnails/drawings/page-33.jpg",
  "./Thumbnails/drawings/page-34.jpg",
  "./Thumbnails/drawings/page-35.jpg",
  "./Thumbnails/drawings/page-36.jpg",
  "./Thumbnails/drawings/page-37.jpg",
  "./Thumbnails/drawings/page-38.jpg",
  "./Thumbnails/drawings/page-39.jpg",
  "./Thumbnails/drawings/page-40.jpg",
  "./Thumbnails/drawings/page-41.jpg",
  "./Thumbnails/drawings/page-42.jpg",
  "./Thumbnails/drawings/page-43.jpg",
  "./Thumbnails/drawings/page-44.jpg",
  "./Thumbnails/drawings/page-45.jpg",
  "./Thumbnails/drawings/page-46.jpg",
  "./Thumbnails/drawings/page-47.jpg",
  "./Thumbnails/drawings/page-48.jpg",
  "./Thumbnails/drawings/page-49.jpg",
  "./Thumbnails/drawings/page-50.jpg",
  "./Thumbnails/drawings/page-51.jpg",
  "./Thumbnails/drawings/page-52.jpg",
  "./Thumbnails/drawings/page-53.jpg",
  "./Thumbnails/drawings/page-54.jpg",
  "./Thumbnails/drawings/page-55.jpg",
  "./Thumbnails/drawings/page-56.jpg",
  "./Thumbnails/drawings/page-57.jpg",
  "./Thumbnails/drawings/page-58.jpg",
  "./Thumbnails/drawings/page-59.jpg",
  "./Thumbnails/drawings/page-60.jpg",
  "./Thumbnails/drawings/page-61.jpg",
  "./Thumbnails/drawings/page-62.jpg",
  "./Thumbnails/drawings/page-63.jpg",
  "./Thumbnails/drawings/page-64.jpg",
  "./Thumbnails/drawings/page-65.jpg",
  "./Thumbnails/drawings/page-66.jpg",
  "./Thumbnails/drawings/page-67.jpg",
  "./Thumbnails/drawings/page-68.jpg",
  "./Thumbnails/drawings/page-69.jpg",
  "./Thumbnails/drawings/page-70.jpg",
  "./Thumbnails/drawings/page-71.jpg",
  "./Thumbnails/drawings/page-72.jpg",
  "./Thumbnails/drawings/page-73.jpg",
  "./Thumbnails/drawings/page-74.jpg",
  "./Thumbnails/drawings/page-75.jpg",
  "./Thumbnails/drawings/page-76.jpg",
  "./Thumbnails/drawings-hd/page-01.jpg",
  "./Thumbnails/drawings-hd/page-02.jpg",
  "./Thumbnails/drawings-hd/page-03.jpg",
  "./Thumbnails/drawings-hd/page-04.jpg",
  "./Thumbnails/drawings-hd/page-05.jpg",
  "./Thumbnails/drawings-hd/page-06.jpg",
  "./Thumbnails/drawings-hd/page-07.jpg",
  "./Thumbnails/drawings-hd/page-08.jpg",
  "./Thumbnails/drawings-hd/page-09.jpg",
  "./Thumbnails/drawings-hd/page-10.jpg",
  "./Thumbnails/drawings-hd/page-11.jpg",
  "./Thumbnails/drawings-hd/page-12.jpg",
  "./Thumbnails/drawings-hd/page-13.jpg",
  "./Thumbnails/drawings-hd/page-14.jpg",
  "./Thumbnails/drawings-hd/page-15.jpg",
  "./Thumbnails/drawings-hd/page-16.jpg",
  "./Thumbnails/drawings-hd/page-17.jpg",
  "./Thumbnails/drawings-hd/page-18.jpg",
  "./Thumbnails/drawings-hd/page-19.jpg",
  "./Thumbnails/drawings-hd/page-20.jpg",
  "./Thumbnails/drawings-hd/page-21.jpg",
  "./Thumbnails/drawings-hd/page-22.jpg",
  "./Thumbnails/drawings-hd/page-23.jpg",
  "./Thumbnails/drawings-hd/page-24.jpg",
  "./Thumbnails/drawings-hd/page-25.jpg",
  "./Thumbnails/drawings-hd/page-26.jpg",
  "./Thumbnails/drawings-hd/page-27.jpg",
  "./Thumbnails/drawings-hd/page-28.jpg",
  "./Thumbnails/drawings-hd/page-29.jpg",
  "./Thumbnails/drawings-hd/page-30.jpg",
  "./Thumbnails/drawings-hd/page-31.jpg",
  "./Thumbnails/drawings-hd/page-32.jpg",
  "./Thumbnails/drawings-hd/page-33.jpg",
  "./Thumbnails/drawings-hd/page-34.jpg",
  "./Thumbnails/drawings-hd/page-35.jpg",
  "./Thumbnails/drawings-hd/page-36.jpg",
  "./Thumbnails/drawings-hd/page-37.jpg",
  "./Thumbnails/drawings-hd/page-38.jpg",
  "./Thumbnails/drawings-hd/page-39.jpg",
  "./Thumbnails/drawings-hd/page-40.jpg",
  "./Thumbnails/drawings-hd/page-41.jpg",
  "./Thumbnails/drawings-hd/page-42.jpg",
  "./Thumbnails/drawings-hd/page-43.jpg",
  "./Thumbnails/drawings-hd/page-44.jpg",
  "./Thumbnails/drawings-hd/page-45.jpg",
  "./Thumbnails/drawings-hd/page-46.jpg",
  "./Thumbnails/drawings-hd/page-47.jpg",
  "./Thumbnails/drawings-hd/page-48.jpg",
  "./Thumbnails/drawings-hd/page-49.jpg",
  "./Thumbnails/drawings-hd/page-50.jpg",
  "./Thumbnails/drawings-hd/page-51.jpg",
  "./Thumbnails/drawings-hd/page-52.jpg",
  "./Thumbnails/drawings-hd/page-53.jpg",
  "./Thumbnails/drawings-hd/page-54.jpg",
  "./Thumbnails/drawings-hd/page-55.jpg",
  "./Thumbnails/drawings-hd/page-56.jpg",
  "./Thumbnails/drawings-hd/page-57.jpg",
  "./Thumbnails/drawings-hd/page-58.jpg",
  "./Thumbnails/drawings-hd/page-59.jpg",
  "./Thumbnails/drawings-hd/page-60.jpg",
  "./Thumbnails/drawings-hd/page-61.jpg",
  "./Thumbnails/drawings-hd/page-62.jpg",
  "./Thumbnails/drawings-hd/page-63.jpg",
  "./Thumbnails/drawings-hd/page-64.jpg",
  "./Thumbnails/drawings-hd/page-65.jpg",
  "./Thumbnails/drawings-hd/page-66.jpg",
  "./Thumbnails/drawings-hd/page-67.jpg",
  "./Thumbnails/drawings-hd/page-68.jpg",
  "./Thumbnails/drawings-hd/page-69.jpg",
  "./Thumbnails/drawings-hd/page-70.jpg",
  "./Thumbnails/drawings-hd/page-71.jpg",
  "./Thumbnails/drawings-hd/page-72.jpg",
  "./Thumbnails/drawings-hd/page-73.jpg",
  "./Thumbnails/drawings-hd/page-74.jpg",
  "./Thumbnails/drawings-hd/page-75.jpg",
  "./Thumbnails/drawings-hd/page-76.jpg"
];

self.addEventListener('install', event => {
  event.waitUntil(
    caches.open(CACHE_NAME).then(cache => cache.addAll(ASSETS)).then(() => self.skipWaiting())
  );
});

self.addEventListener('activate', event => {
  event.waitUntil(
    caches.keys().then(keys =>
      Promise.all(keys.filter(k => k !== CACHE_NAME).map(k => caches.delete(k)))
    ).then(() => self.clients.claim())
  );
});

self.addEventListener('fetch', event => {
  // Let Firebase and external CDN requests go straight to the network
  const url = event.request.url;
  if (url.includes('firebaseio.com') || url.includes('googleapis.com') || url.includes('gstatic.com')) {
    return; // don't intercept — let browser handle normally
  }
  event.respondWith(
    caches.match(event.request).then(cached => cached || fetch(event.request))
  );
});
